### ISSUE TITLE
Add Invoice to Purchase (pdf)

### ISSUE THREAD

**Issue by sHorst** [ArnesSI/netbox-inventory#102]
it would be great, if i could add an invoice to the Purchase. This could be either one or multiple PDF Files.

**Comment by matejv** [comment]
That seems like a reasonable request.

As far as I'm aware the core netbox does not allow file uploads to objects other than images. So there might a bit more work to handle this than it seems at first glance. But I'll take a look.

**Comment by matejv** [comment]
For this use case I recommend use of [netbox-attachments](https://github.com/Kani999/netbox-attachments) plugin. I just made changes in templates to allow the use of netbox_attachments with netbox_inventory objects.

You'll need to configure it, see README of netbox_attachments. This worked in my tests:

```py
PLUGINS = [
    'netbox_inventory',
    'netbox_attachments',
]

PLUGINS_CONFIG = {
    'netbox_attachments': {
        'apps': ['netbox_inventory',],
        'display_setting': {
            "netbox_inventory.purchase": "right_page",
            "netbox_inventory.supplier": "left_page",
            "netbox_inventory.asset": "full_width_page",
            "netbox_inventory.inventoryitemtype": "full_width_page",
            "netbox_inventory.inventoryitemgroup": "full_width_page",
        },
    },
}
```

Use `right_page`, `left_page` or `full_width_page` as you see fit.

**Comment by sHorst** [comment]
will have a look into this. thx for the hint
