### ISSUE TITLE
Possible to support software assets?

### ISSUE THREAD

**Issue by aevans1987** [ArnesSI/netbox-inventory#104]
Pretty much as in the title, could this be extended to support software and software license management?

**Comment by matejv** [comment]
What exactly would all this entail?

We have only limited use for managing licenses - when we need to manage license levels of routers for example. We model these as inventory item types and we can then assign them to devices as inventory items. This worked well enough for now.

Anything more than that, I feel is out of scope for netbox_inventory and should probably be it's own plugin.

**Comment by matejv** [comment]
Closing due to lack of feedback and probably being out of scope for this plugin.
