### ISSUE TITLE
Feature request: add status "delivery pending"

### ISSUE THREAD

**Issue by cs-1** [ArnesSI/netbox-inventory#109]
Can you please add the status "delivery pending" to assets? This would help with tracking orders of assets until their arrival and would give us a full lifecycle management. This way we can add purchases and assets for a purchase that haven't been delivered yet.

**Comment by matejv** [comment]
You can modify asset status choices through configuration. See bottom of [available settings](https://github.com/ArnesSI/netbox-inventory#available-settings) section in readme for an example. And for more documentation see netbox [FIELD_CHOICES](https://docs.netbox.dev/en/stable/configuration/data-validation/#field_choices)

**Comment by cs-1** [comment]
Sorry, you're perfectly right, I didn't read to the end of the table. My mistake.
