### ISSUE TITLE
assign and reassign forms show custom fields

### ISSUE THREAD

**Issue by matejv** [ArnesSI/netbox-inventory#120]
Assign asset to device form will show custom fields for asset, which doesn't make sense to show. Also Reassign a different asset to device shows custom fields for device, which also makes no sense.

This is because `AssetDeviceAssignForm` and `AssetDeviceReassignForm` inherit from `NetBoxModelForm` that includes those fields by default. (It also includes tags field which we hide)

Investigate how difficult it would be to use a non-model form for assign and reassign operations.

**Comment by Kani999** [comment]
The same issue appears for `AssetModuleReassignForm` `AssetModuleAssignForm` and `AssetInventoryItemReassignForm` `AssetInventoryItemAssignForm` which inherit from `AssetReassignMixin` `AssetAssignMixin`

Removing custom fields while initialization should work the same as for tags.
PR opened #131

**Comment by matejv** [comment]
fixed by #131 Thank you!
