### ISSUE TITLE
Usage history of inventory items / modules

### ISSUE THREAD

**Issue by GuiliSab** [ArnesSI/netbox-inventory#125]
Hello,

Is it possible to add a feature for tracking usage of all inventory items / modules ?
Per example, if I have some RAM in a server, I keep it when the server is dead and use the RAM in another server.
Is it possible to have history telling me where my RAM was used previously ?
Same thing with SFP, hard drives, network cards, CISCO modules, etc ...
We use this information for knowing how many times an item has been pluged / unplugged or having a suspicious failure.

A table with lines composed by start and end date of use, reason of unplugged will be great.

Thank you.

**Comment by cs-1** [comment]
You could use the "Journal" tab. The Journal allows you to record the history of an item (not only in netbox-inventory but also e.g. for devices in NetBox. We use the Journal tab for the administrative history of devices and items.

**Comment by GuiliSab** [comment]
Humm, okay.
I'm a noob in netbox so I wasn't aware of that ... I see what I can do.
When creating / updating an inventory items, make an API call via webhooks to add entry log to device / inventory item.
Yeah, we don't need anything more.

So, I close the issue.
Thank you for the reply.
