### ISSUE TITLE
"Deliveries" table in Purchases view doesn't show correct asset count

### ISSUE THREAD

**Issue by cs-1** [ArnesSI/netbox-inventory#126]
NetBox version: v3.6.0
netbox-inventory version: v1.5.0

First of all: thanks for the "Deliveries" table in the Purchases view! :)

One minor issue: the "Assets" column always shows zero even for deliveries that show assets when clicking on them.

**Comment by matejv** [comment]
Whoops, I hadn't noticed that. netbox started including tables in views using HTMX, possibly to also get around issues like this. I'll do something similar to fix this.
