### ISSUE TITLE
API Endpoint to assign device

### ISSUE THREAD

**Issue by shepherdjay** [ArnesSI/netbox-inventory#127]
Apologies -- I couldn't find if this was covered or not and did some of the exploration of the codebase and api but plugin development in netbox is still a little new to me. 

Is there an API method of assigning an asset to a device? I'm able to pull a list of assets and I see in the API for each asset there is a `device` dictionary that appears that includes the device `id`, `url`, `display`, and `name` but it isn't clear if this is safe to just update this or if there is a better endpoint for doing a programmatic assignment.

Got myself into this situation because of doing a bulk import where we bulk imported the devices separately from the assets and would like to avoid manually trying to reassign.

**Comment by cs-1** [comment]
It's easily done e.g. in Python:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import pynetbox

nb = pynetbox.api("https://your.netbox.server.here", token="your_token_that_can_change_assets")
asset = nb.plugins.inventory.assets.get(id=1234)
device = nb.dcim.devices.get(id=9876)
asset.device = device
asset.save()

```

Of course you can use any other criteria than ID to get the asset and the device like "name".
