### ISSUE TITLE
Bill create for purchases

### ISSUE THREAD

**Issue by ryanmerolle** [ArnesSI/netbox-inventory#13]
If I were to order 200 sfps, it’s not ideal to either us the api ot ui to bulk create the items.

I think it would be useful to allow bulk creation of inventory items given a quantity, order number and inventory item type.

it could be useful to allow the same feature for marking items as used, but admittedly that is not tricky if inventory items have a serial.

**Comment by matejv** [comment]
We could do it the way netbox does for adding interfaces and other components. Some fields support a special syntax where you give a range of values and netbox creates an instance for each value in range. For example you could got to Add asset and in name field you'd specify `sfp [1-200]`. That would create 200 assets with names like `sfp 1`, `spf 2`... I think the following fields could support this syntax: `name`, `asset_tag`, `serial`.

Would that be acceptable?

Another way I suppose we could do is to have a separate form for bulk add with quantity field. Here you couldn't specify asset_tag or serial fields as these must be empty or unique (for a given inventoryitem type).

**Comment by ryanmerolle** [comment]
Either way works

**Comment by matejv** [comment]
I have implemented this in #24
