### ISSUE TITLE
git not included in netbox docker

### ISSUE THREAD

**Issue by ytjohn** [ArnesSI/netbox-inventory#136]
This is more of a note, potential doc update.

**EDIT: I should clarify this only impacts if you're installing the development version direct from git.**

During an setup of netbox 3.6.4 in docker, I got an error that a git was not installed.

I worked around this by adding a line in Dockerfile-Plugins
```docker
FROM netboxcommunity/netbox:latest
RUN apt update; apt install -y git
```

I tried to figure out when this went away.  I found two commits of interest:

June 10th, 2022 they moved from [arch to debian](
https://github.com/netbox-community/netbox-docker/commit/9e2f4313fb4c2fc60906739950f2ee92710b0759) which explicitly drops the git package. 

Then in July 19th, 2022 they moved from [debian to ubuntu](https://github.com/netbox-community/netbox-docker/commit/45e7f6a30c2187d53da79b1580d606ae0101d5d4).

I tested debian:bullseye-slim, debian:11-slim, and ubuntu:22.04 - none have git installed. 

A cleaner way to do this (less bloat) is to update your local copy of [Dockerfile](https://github.com/netbox-community/netbox-docker/blob/release/Dockerfile) and add git to the apt-get install list. The downside is that this fill will get overwritten next time you pull from the git repo.

**Comment by matejv** [comment]
Thank you. I've updated the README to use archive URLs instead of git.
