### ISSUE TITLE
Installed Location

### ISSUE THREAD

**Issue by sufiyan04** [ArnesSI/netbox-inventory#138]
I notice that when viewing an asset, the Installed Location section displays related fields such as Site, Location, Rack, and Device. However, during the process of adding or editing an asset, I do not find options to specify the installed location. While adding an asset, I only observe fields for storage site and location. Furthermore, even after updating the storage site, it doesn't seem to reflect or associate with the asset.
 
I am running netbox version 3.6.3.

**Comment by matejv** [comment]
Installed location and storage locations are separate on purpose.

When defining an asset you define where it's usually stored when not in use. Then when you go and use it, you assign it to a netbox device, module or inventory item. When you do that the asset's installed location is automatically determined by the netbox device (or module or inventory item) location.
