### ISSUE TITLE
Show related assets throughout netbox

### ISSUE THREAD

**Issue by matejv** [ArnesSI/netbox-inventory#14]
On detail views of core netbox models add a table with assets related to that object. Some places this might make sense:

- Contact - to show assets assigned to a particular contact
- Tenant - to show assets assigned to a particular tenant or owned by that tenant
- DeviceType - show Assets that have that device type (same for module type & inventory item type)
- Manufacturer - show Assets made by manufacturer (via device_type, module_type and inventoryitem_type)

**Comment by ryanmerolle** [comment]
- Site
- Location

**Comment by ryanmerolle** [comment]
I can work on some cards for this if you like in those models.
