### ISSUE TITLE
New Supplier Feature: Vendor Transactions

### ISSUE THREAD

**Issue by gpmidi** [ArnesSI/netbox-inventory#144]
I'm thinking of adding an import option. It'd be a supplier page feature that takes an export from a vendor and adds all the transactions to the Purchases and Deliveries tables. I'm thinking of supporting Amazon and eBay data exports out of the gate. Any thoughts?

**Comment by matejv** [comment]
There are already import options for Suppliers, Purchases and Deliveries. They accept [multiple formats](https://docs.netbox.dev/en/stable/getting-started/populating-data/#bulk-import-csvyaml) in line with the rest of netbox. There is also the option of using [REST API](https://docs.netbox.dev/en/stable/plugins/development/rest-api/) or netbox [custom scripts](https://docs.netbox.dev/en/stable/customization/custom-scripts/) to facilitate special kinds of imports some user may want.

I really don't think we need a specialized import function for certain vendor data.
