### ISSUE TITLE
Support for Netbox 3.7

### ISSUE THREAD

**Issue by ytjohn** [ArnesSI/netbox-inventory#150]
Hi,

I've been using this fantastic plugin with netbox 3.6 and upgraded through 3.7 series over the last couple of months without issue.  I saw the 3.6 upgrade required code changes, but 3.7 has "just worked" for us. I'd like to get the compatibility matrix updated to include 3.7.  I'd be willing to do any additional testing desired to fully confirm compatibility.

**Comment by uck9** [comment]
One issue I've just come across is the inability to attach images to Asset Objects when moving to V3.7.X.  Run tests against v3.6.9 and all works ok.  Moving to 3.7.0 causes a popup with the message ' Image attachments cannot be assigned to this object type (netbox_inventory | asset).'.  Taking a look atm to see if I can find why this error is occuring.

**Comment by uck9** [comment]
Added a PR to correct the image attachment issue.  Looks like the attachments have moved to a Mixin which needs to be included in the model instead of a specific reference within the model.

**Comment by jessedufrene** [comment]
I also have the image attachment issue, running v1.5.2 of this plugin with netbox 3.7.5

![image](https://github.com/ArnesSI/netbox-inventory/assets/2367033/b008b93e-49d7-42a7-a4ea-b3ce27fb698f)

**Comment by matejv** [comment]
Fixed in  #151 by @uck9 

I'll release version 1.6.0 later today that will have this fixed. Apologies for the long wait.
