### ISSUE TITLE
Supplier Contact

### ISSUE THREAD

**Issue by ElonLP** [ArnesSI/netbox-inventory#154]
Hey there,
In the Supplier Page is an Tab Contacts, butt if I want to add an Contact I got an Error.

" Contacts cannot be assigned to this object type (netbox_inventory | supplier). "

Is it Possible to change this? I think it is good to have this feature to store some contact informations of the supplier.

**Comment by uck9** [comment]
Assume you're using NetBox 3.7 here?  Feels similar to the issue seen with the attachment of photo's to assets when running in NB 3.7

**Comment by matejv** [comment]
Fixed in #155 

Will be released in version 1.6.0
