### ISSUE TITLE
Allow deliveries without purchase

### ISSUE THREAD

**Issue by alehaa** [ArnesSI/netbox-inventory#160]
Sometimes there can be deliveries with no specific purchase. An example would be waranty hardware replacements. I therefore suggest making `Delivery.purchase` an optional field.

**Comment by matejv** [comment]
Should a Delivery without purchase have a Supplier or not? Do we need to add `Delivery.supplier` field?

**Comment by alehaa** [comment]
Hmm. Good point, I hadn't thought of that. It would make sense to have a supplier, since someone has to send the parts.

Perhaps another (and cleaner) way to implement this would be to use purchases linked to the warranty case instead of having a price attached? However, in this case I think we should add an option to select a manufacturer instead of a supplier for the purchase if the hardware is shipped directly from the manufacturer?

**Comment by alehaa** [comment]
I'll close this. Giving some thoughts on it, this is a rare use case. In this case a purchase without price can be added and the supplier selected. If there's no supplier for some reason, it needs to be added as for other NetBox models. This would be much simpler than changing the code of this plugin.
