### ISSUE TITLE
Update for Netbox 4

### ISSUE THREAD

**Issue by LilTrublMakr** [ArnesSI/netbox-inventory#164]
More of an FYI than an issue.

Netbox 4 dropped today. I am expecting that it probably broke all plugins since it is a major version change.

**Comment by LilTrublMakr** [comment]
https://docs.netbox.dev/en/stable/plugins/development/migration-v4/

**Comment by matejv** [comment]
netbox-invnetory release for netbox 4.0 should be ready shortly.
