### ISSUE TITLE
Error during Ugrade to 4.0

### ISSUE THREAD

**Issue by marcucci-DAE** [ArnesSI/netbox-inventory#166]
When I try to run ./upgrade.sh i receive the following error

![image](https://github.com/ArnesSI/netbox-inventory/assets/94970527/2f856a35-0b61-4963-b5a0-9fcfd0e8031a)

Collecting importlib (from netbox-secretstore->-r local_requirements.txt (line 14))
  Using cached importlib-1.0.4.zip (7.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by a084ed22** [comment]
This is an issue specific to your environment and/or another plugin rather than from netbox-inventory, which is however not yet compatible with netbox 4.0
