### ISSUE TITLE
Adding id to searched attributes in asset listing

### ISSUE THREAD

**Issue by cs-1** [ArnesSI/netbox-inventory#173]
Hi all,

I've created pull request https://github.com/ArnesSI/netbox-inventory/pull/172 which adds "id" to the searched attributes in the asset listing. The idea is that the asset ID is often used to identify assets in the field. Enabling searching for the ID helps with managing assets in NetBox. It'd be great if you could add the patch. (Tested against NetBox v4.0.3, works.)

**Comment by matejv** [comment]
thank you
