### ISSUE TITLE
Versão 1.6.x

### ISSUE THREAD

**Issue by Matheus04chagas** [ArnesSI/netbox-inventory#175]
Estou com um problema na versão 4.0 do netbox em relação a plugins. Precisava da versão 1.6 desse plugin pois estou na versão 3.7 do netbox, mas não encontro aqui, alguém pode me ajudar?

-----------------------------------------------------------------------------------------

I have a problem in version 4.0 of netbox regarding plugins. I needed version 1.6 of this plugin because I'm on version 3.7 of netbox, but I can't find it here, can anyone help me?

**Comment by matejv** [comment]
closing as @cs-1 answer is sufficient
