### ISSUE TITLE
Ability to override the Asset Name with the Assigned Device's Name

### ISSUE THREAD

**Issue by moetezz** [ArnesSI/netbox-inventory#195]
Add a config parameter same for sync the S/n and Asset tag to their respective in the Device View, This function will be the other way around where the Name Field can optionally take the Name of the Device. I think It would be helpful for identification purposes, or for example let's you name an unused asset as Spare switch 023, and it is going to be used you want to automatically remove the Spare 023  as name since it is being used.

Let me know if you think this will be useful. Of course it should optional.(True or False )

**Comment by matejv** [comment]
I'm not too keen on this feature. Just getting sync of S/N & asset tag to work asset to device was surprisingly difficult. Handling additional data in reverse at the same time sounds like a nightmare.

Here's a few questions I thought of when thinking about this for a bit (there are probably more I haven't thought of):

What should happen if a device is deleted? And what if a device is kept and only the assignment of device - asset changes? What should we do with modules and inventory items? Do we use just their names or do we consider device name as well? Also devices in netbox have optional names.

And in the end of it all - throughout the UI netbox_inventory shows what device, module etc is assigned to an asset. You can even see this in tables via Hardware column. So copying names to assets would mostly just duplicate this info.

If you have just a narrow use case of updating asset name from device - Have you considered using [Event Rules](https://netboxlabs.com/docs/netbox/en/stable/features/event-rules/) to run a custom script that would update asset name for you?
