### ISSUE TITLE
Filtering by None/null device on asset endpoint yields ValueError

### ISSUE THREAD

**Issue by sylvia-cs** [ArnesSI/netbox-inventory#197]
### Netbox Version
v3.4.8

### Issue
Selecting ‘None’ option for device in /assets endpoint triggers ValueError on Netbox side. Attempted workaround by setting installed_device_name=null in request also fails with empty results (appears to be searching for string "null" rather than value null).
![Screenshot 2024-09-25 at 3 27 51 PM](https://github.com/user-attachments/assets/f727459e-d037-4ae9-9a87-166de66a1c54)
![Screenshot 2024-09-25 at 3 28 01 PM](https://github.com/user-attachments/assets/dd3d80ff-e34d-48cd-aa3e-6bf1bc078754)
![Screenshot 2024-09-25 at 3 30 09 PM](https://github.com/user-attachments/assets/9b85b6f2-7ca0-43fe-9807-b7f3f87b59e3)

**Comment by matejv** [comment]
Thank you for reporting this. For now you can use `Is assigned to hardware : No` filter to get only assets that aren't installed for example. 

But the issues should be fixed, I agree. The logic for filtering assets on installed device, location, site, etc. has gotten quite complex, so I'll have to take a bit more time to fix this.

Note to self: all filters that use `query_located()` need to be checked.
