### ISSUE TITLE
New Filter for Assets by "Contact Group"

### ISSUE THREAD

**Issue by proudbro** [ArnesSI/netbox-inventory#198]
Hi,

Currently, assets can only be filtered by **Contacts**
Could you please add the possibility to filter assets by **Contact Group** in the Usage section?
![image](https://github.com/user-attachments/assets/6ddf3390-1735-4345-b5c3-10c46c801846)

**Comment by matejv** [comment]
This is now in the latest plugin release. Sorry for the delay.
