### ISSUE TITLE
Can't find module

### ISSUE THREAD

**Issue by lordspirit** [ArnesSI/netbox-inventory#28]
Hi there,

Im trying to add netbox-inventory in a fresh netbox install. Everything is working fine until I change configuration.py file with indicated settings. Those are my errors.

[Files attached]

Any hints please? 
I've tried with netbox_inventory and netbox-inventory, with all ' ' and " ".
[netbox_error.txt](https://github.com/ArnesSI/netbox-inventory/files/10068372/netbox_error.txt)

**Comment by lordspirit** [comment]
Solved. 
Executed commands as root and went as planned! Thanks a lot

**Comment by matejv** [comment]
Yes generally you want to install packages in a virtual environment with the same privileges as use to create the environment. [Official Netbox instructions](https://docs.netbox.dev/en/stable/installation/3-netbox/#run-the-upgrade-script) use sudo, so installing plugins should too. I'll put a not in the README.

Glad you got it working, best of luck!

**Comment by lordspirit** [comment]
Thanks a lot m8.
