### ISSUE TITLE
Order number model

### ISSUE THREAD

**Issue by ryanmerolle** [ArnesSI/netbox-inventory#4]
1.) In its current state the order number does not show up in the ui, just the edit form.

2.) if you are going to track order number, make its own model so you can see all assets from an order number.

3.) It should extend to devices.

**Comment by matejv** [comment]
I've added a separate model as you suggested (in #10). 

On the Asset view I still need to add a bunch of stuff, nit just the order/purchase info. I'll tackle that later.
