### ISSUE TITLE
Netbox 3.4 Top Level Navigation

### ISSUE THREAD

**Issue by ryanmerolle** [ArnesSI/netbox-inventory#44]
netbox-community/netbox#9071 added support for plugins to insert top level navigation.

**Comment by vrelk** [comment]
I just made the changes for myself and created a [pull request](https://github.com/ArnesSI/netbox-inventory/pull/48) for it.

**Comment by matejv** [comment]
merged and made it configurable in #57 Will be part of next plugin release
