### ISSUE TITLE
Ability to quickly mark an asset as status used

### ISSUE THREAD

**Issue by ryanmerolle** [ArnesSI/netbox-inventory#45]
It would be nice for the various asset views to provide a quick access button in line of the table to mark an asset status as used.

**Comment by matejv** [comment]
Makes sense, and should be easily doable.

**Comment by matejv** [comment]
Well, it might not be as easy as I thought.

For example - netbox has in Interface table a button "Mark planned" or "Mark connected". This button is only enabled if there is a cable connected. And clicking it toggles the status field of connected cable.

I thought I could implement a similar functionality. Unfortunately this requires some javascript code to figure out the state that should be set and to send the API request in the background (see [connectionToggle.ts](https://github.com/netbox-community/netbox/blob/develop/netbox/project-static/src/buttons/connectionToggle.ts). So this is not some reusable component.

Also there is no way (as I'm aware) to include javascript code as part of a plugin.

So, any ideas how to implement this another way are welcome :)
