### ISSUE TITLE
Add Images to Assets and Inventory Item Types

### ISSUE THREAD

**Issue by Starkstromkonsument** [ArnesSI/netbox-inventory#46]
One can attach images to devices:

![grafik](https://user-images.githubusercontent.com/53019449/212492282-1d2e41fd-9ee0-4068-8f96-92510a59f90e.png)

It would be great if this would be implemented for Assets and Inventory Item Types too, as it can not be achieved using custom fields. Thank you!

**Comment by matejv** [comment]
Thank you for the suggestion. This will be part of the next release.
