### ISSUE TITLE
Inventory Group groupings

### ISSUE THREAD

**Issue by ryanmerolle** [ArnesSI/netbox-inventory#49]
I hate open ended feature requests, I generally like to have the model updates in mind.

Unfortunately, I do not quite know how to tackle this.

I want to add some sort of extra organization of item groups and item types.  I track SFP-1G-LX, SFP-1G-T, SFP-1G-SX as inventory groups, and get to specific model/manufacturer tracking using inventory item types.  It would be nice to get a view or be able to filter on another level of grouping such as SFP or SFP-1G.  You could tackle this a few ways:
- Allow nesting / parents similar to models like region, site_group, and soon to be roles
- User just adds custom fields to either inventory item groups or inventory item types. Or if useful at the to plugin's model.

What are your thoughts?

**Comment by matejv** [comment]
(sorry for not responding to this and other issues sooner, I am currently busy with other work project,I hope to get back to this plugin soon)

We had a similar discussion internally. I believe it would make most sense to allow nesting of inventory item group instances. Also, I think netbox already provides all the tooling needed to make this possible and easy to use.
