### ISSUE TITLE
Adding a new element throws an exception

### ISSUE THREAD

**Issue by drobnymichal** [ArnesSI/netbox-inventory#55]
When I try to add a new inventory item to the device using the button "Create hardware from asset" an error occurs:

```
<class 'AttributeError'>

'NoneType' object has no attribute 'get'

Python version: 3.10.6
NetBox version: 3.4.3
```

The error is associated with line 161 in the forms/create.py file. In my opinion, this is because 'super().clean()' returns None instead of a dictionary.

```python:
def clean(self):
    cleaned_data = super().clean()
    component_set = None
    for field_name in COMPONENT_FIELDS:
        field_value = cleaned_data.get(field_name)
        if field_value and component_set:
            raise ValidationError('Only a single component can be selected')
        if field_value:
            component_set = field_name
            cleaned_data['component_type'] = ContentType.objects.get(app_label='dcim', model=field_name)
            cleaned_data['component_id'] = field_value.pk
            cleaned_data.pop(field_name)
    return cleaned_data
```

Could you please fix this problem?

**Comment by matejv** [comment]
It looks like this change in netbox v3.4.2 https://github.com/netbox-community/netbox/issues/11156 changed the `InventoryItemForm.clean()` method. I'll have to check how to fix my implementation.

**Comment by drobnymichal** [comment]
Thank you for fixing this bug.
