### ISSUE TITLE
Importing devices with API

### ISSUE THREAD

**Issue by ultrapista** [ArnesSI/netbox-inventory#60]
Would like to ask you, if there is an option to create new assets with API. Im having an issue creating new asset in Python with the following error: `{'module_type': ['This field may not be null.'], 'module': ['This field may not be null.'], 'storage_location': ['This field may not be null.'], 'purchase': ['This field may not be null.']}`. Also in Swagger the POST method is unresponsive (plugins/inventory/assets).

**Comment by matejv** [comment]
Indeed, it seems the API is broken for creating / editing Assets at the moment. Thanks for reporting this. I'm working on a fix.

**Comment by ultrapista** [comment]
It seems that even after the fix, it still does not work me. The error message is the same: `pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'module_type': ['This field may not be null.'], 'module': ['This field may not be null.'], 'storage_location': ['This field may not be null.'], 'purchase': ['This field may not be null.']}` I have noticed that in Netbox Swagger the execute button for POST /plugins/inventory/assets/ is unresponsive (did not work before the fix either).

**Comment by matejv** [comment]
I have not released the new version onto pypi yet. I plan to do so later today or tomorrow. Have you tested the plugin installed from git?

If you're testing against master branch and it still doesn't work, please write a code sample that errors out for you, so I can test myself. I'm currently testing and it seems to work fine.

**Comment by drobnymichal** [comment]
Hi,

I am trying the same thing in Swagger UI and I got this response:

RESPONSE BODY
```json
{
  "device": [
    "This field may not be null."
  ],
  "module_type": [
    "This field may not be null."
  ],
  "module": [
    "This field may not be null."
  ],
  "inventoryitem_type": [
    "This field may not be null."
  ],
  "inventoryitem": [
    "This field may not be null."
  ],
  "tenant": [
    "This field may not be null."
  ],
  "contact": [
    "This field may not be null."
  ],
  "storage_location": [
    "This field may not be null."
  ],
  "owner": [
    "This field may not be null."
  ],
  "purchase": [
    "This field may not be null."
  ]
}
```

REQUEST DATA
```json
{
  "name": "test",
  "asset_tag": "test",
  "serial": "aaa",
  "status": "stored",
  "device_type": 1,
  "device": null,
  "module_type": null,
  "module": null,
  "inventoryitem_type": null,
  "inventoryitem": null,
  "tenant": null,
  "contact": null,
  "storage_location": null,
  "owner": null,
  "purchase": null,
  "warranty_start": null,
  "warranty_end": null,
  "comments": "",
  "tags": []
}
```
CURL
```
curl -X 'POST' \
  'http://127.0.0.1:8000/api/plugins/inventory/assets/' \
  -H 'accept: application/json' \
  -H 'Authorization: TOKEN' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFToken: CSRF-TOKEN' \
  -d '{
  "name": "test",
  "asset_tag": "test",
  "serial": "aaa",
  "status": "stored",
  "device_type": 1,
  "device": null,
      "module_type": null,
      "module": null,
      "inventoryitem_type": null,
      "inventoryitem": null,
      "tenant": null,
      "contact": null,
      "storage_location": null,
      "owner": null,
      "purchase": null,
      "warranty_start": null,
      "warranty_end": null,
      "comments": "",
      "tags": []
}'
```

**Comment by matejv** [comment]
OK, I see the problem now. I've always just omitted the keys I did not set. Never tried setting them to null explicitly.

I'll have the fix ready shortly.
