### ISSUE TITLE
Edit any property of an Inventory Item linked to an Asset fails if sync_hardware_serial_asset_tag = True

### ISSUE THREAD

**Issue by Starkstromkonsument** [ArnesSI/netbox-inventory#81]
If you set sync_hardware_serial_asset_tag = True and try to edit any property of an Inventory Item that is linked to an Asset (or even just click on Inventory Item > Edit and Save without touching anything) saving fails with this error message:
![grafik](https://user-images.githubusercontent.com/53019449/230729133-692e69d6-cbb8-426c-954d-f829d7050bfe.png)

**Comment by matejv** [comment]
This was caused by incorrectly comparing asset and inventory item serial numbers when they were blank.

The cause was the same as in #80 and is fixed by #85
