### ISSUE TITLE
Readme.md > Settings: inconsistency between Example settings and Available settings

### ISSUE THREAD

**Issue by Starkstromkonsument** [ArnesSI/netbox-inventory#82]
The Example settings include two options that are not included in the table for Available settings:

![grafik](https://user-images.githubusercontent.com/53019449/230729383-40ec80f9-7574-4ea2-9442-6e94f4c7c83b.png)

Are these deprecated or just missing under available settings?

**Comment by matejv** [comment]
Ah, looks like I forgot to update the example config when changing settings.. The table of available settings is correct and I'll update the example as well. Thank you for that.
