### ISSUE TITLE
Edit Assignment Broken for Inventory Items

### ISSUE THREAD

**Issue by jonathanspw** [ArnesSI/netbox-inventory#90]
The edit assignment functionality seems to be broken as of NetBox 3.4.8, perhaps earlier.

The edit can be submitted and no errors are thrown, but the assignment is not updated.

Perhaps it's related to https://github.com/netbox-community/netbox/issues/11432 from the 3.4.8 changelog.

**Comment by matejv** [comment]
I've tested this just now under netbox v3.4.8 and netbox-inventory v1.2.3 and it seems to be working or me.

Could you give a more detailed description of steps you perform when it's not working? What version of netbox.inventory are you running and that are your settings under `PLUGINS_CONFIG['netbox_inventory']`?

**Comment by danielcp00** [comment]
Howdy, 

netbox v3.4.8 and netbox-inventory v1.2.3, all default configs nothing defined. 
Process we're using is pretty straight forward. 

Create a new asset, so Assets -> Add 

Name: Test1
Asset Tag: 12345
Status: Stored
Manufacturer: Intel
Inventory item type: D3-S4510

All other fields blank. 

This creates asset ID 12

Next, use "Create Inventory Item" 

Select a device (server01)
Give it a name, D3-S4510

All other fields blank, this creates inventory item 17 which shows properly attached to server01 etc.

Now goto Assets -> "Edit Assigned Hardware" , both "Site" and "Device" are blank , but the Inventory Item displays correctly. Change "Device" to server02, a popup shows "Modified asset D3-S4510 (id:12)" but installed location remains server01

**Comment by jonathanspw** [comment]
Can confirm things are working as expected in 3.4.7.

Would you like a PR to update buttons/wording a little bit to clarify the functionality of editing the inventory item association?

**Comment by matejv** [comment]
Sure, that would be most welcome.

I also see netbox developers are working on a fix to again allow changing device of an an inventory item so hopefully this will be fixed soon.

**Comment by nathan-reeves-wel** [comment]
Looks like fix for this was included in v3.4.9.
