### ISSUE TITLE
Asset import ignoring tags

### ISSUE THREAD

**Issue by danielcp00** [ArnesSI/netbox-inventory#91]
Howdy,

Netbox (v3.4.7)
netbox-inventory v 1.2.3

Attempt to set tags using asset imports for adding or updating an item. 

Sample import:

name,serial,status,hardware_kind,manufacturer,model_name,part_number,tags,id
DDR4,xxxx,used,inventoryitem,Samsung,M393,M393,"32gb,2133-mts",9

Asset is created, all items import but tags are ignored.

For testing you can add an invalid/bad tag and it will reject it as the tag not existing.

When the asset is created the changelog shows:

Post-Change Data
name: "DDR4"
tags: []
owner: null
device: null
module: null

When the asset is updated, changing any combination of tags results in is simply saying "Difference No Changes"

**Comment by matejv** [comment]
thank you for reporting this

The issue should be fixed in v1.2.4
